name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  JSON_KEY_FILE: ${{ secrets.JSON_KEY_FILE }}
  GITHUB_WORKSPACE: ${{ secrets.GITHUB_WORKSPACE }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GITHUB_RUN_NUMBER: ${{ secrets.GITHUB_RUN_NUMBER }}
  GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
  GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: build app
        uses: ./.github/build

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: build app
        uses: ./.github/build

      - name: Google Authentication
        run: |
          echo $JSON_KEY_FILE > $GITHUB_WORKSPACE/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/gcloud-service-key.json
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io

      - name: Docker build image
        run: docker build --file=Dockerfile -t $GITHUB_REPOSITORY .

      - name: Docker push image to GCR
        run: |
          docker tag $GITHUB_REPOSITORY gcr.io/$GCP_PROJECT_ID/$GITHUB_REPOSITORY:$GITHUB_SHA-$GITHUB_RUN_NUMBER
          docker push gcr.io/$GCP_PROJECT_ID/$GITHUB_REPOSITORY:$GITHUB_SHA-$GITHUB_RUN_NUMBER
          docker tag $GITHUB_REPOSITORY gcr.io/$GCP_PROJECT_ID/$GITHUB_REPOSITORY:latest
          docker push gcr.io/$GCP_PROJECT_ID/$GITHUB_REPOSITORY:latest

      - name: Deploy Cloud Run
        run: |
          gcloud config set core/project $GCP_PROJECT_ID
          envsubst < docker/service.yaml > ./service.yaml
          gcloud run services replace service.yaml --region=asia-east1
